### ISSUE TITLE
IDStringConst.h Not Found

### ISSUE THREAD

**Issue by AAYuan** [JimmyFung/MyPlanSideslip#1]
hi 项目clone后IDStringConst.h找不到 请问IDStringConst.h是用的三方吗？

**Comment by zealfung** [comment]
你好，这不是第三方，是定义了本应用里面的各种第三方账号id，属于私密信息，所以不上传公开。公布源代码的目的是分享实现思路和逻辑，而不是完完全全不需要做任何处理就可以运行起来了。缺了这个文件，只是很小的一部分内容，仔细稍微改一下代码就可以通过编译和运行起来了。希望对你有帮助。

------------------ Original ------------------
